apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-codefresh
  labels:
    app: nginx-codefresh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-codefresh
  template:
    metadata:
      labels:
        app: nginx-codefresh
    spec:
      containers:
      - name: nginx
        image: gcr.io/crafty-hall-383007/python-app:6622ba65afb4688ed8923de1fd5d018850fa8ea1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
