apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-webserver
spec:
  replicas: 3
  # revisionHistoryLimit>2 not supported right now
  revisionHistoryLimit: 2 
  selector:
    matchLabels:
      app: ngnix-webserver
  template:
    metadata:
      labels:
        app: ngnix-webserver
    spec:
      containers:
        - name: ngnix-webserver
          image: quay.io/codefresh_sa/express:8b1592d
          ports:
            - containerPort: 3000
      imagePullSecrets:
      - name: quay-regcred
  minReadySeconds: 30
