apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-codefresh
  labels:
    app: nginx-codefresh
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: nginx-codefresh
    name: gke-crafty-hall-383007-us-central1-c-cluster-1-test
  source:
    repoURL: https://github.com/prashant8794/pdo-demo-codefresh.git
    targetRevision: main
    path: ./k8s-resources/nginx-app/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
