apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  labels:
    app: nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: nginx-pod-dev
    name: CLUSTER_NAME
  source:
    repoURL: https://github.com/prashant8794/pdo-demo-codefresh.git
    targetRevision: main
    path: ./k8s-resources/nginx-app/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
